### ISSUE TITLE
卡顿

### ISSUE THREAD

**Issue by KarasJoker** [alibaba/Tangram-Android#10]
请教一下大神，滑动的时候卡顿怎么解决

**Comment by longerian** [comment]
卡顿需要你用工具跑一下，查一下瓶颈在哪里，一般情况下是组件本身性能不好，会导致卡顿

**Comment by oldratlee** [comment]
@KarasJoker 问题太笼统了，如 你的问题并不能区分出是你的应用代码还框架的原因引起的。
