### ISSUE TITLE
如何提前初始化View

### ISSUE THREAD

**Issue by tanghb** [alibaba/Tangram-Android#100]
快速滑动的时候，会卡，看了下是因为View在复用池中没有，需要init，有没有预先把这些View给初始化好的方法。。。

**Comment by MikeAfc** [comment]
可以参考下这里复用池的设置，http://pingguohe.net/2017/08/31/vlayout-faq.html，还有是看下你的viewcreate和bind有没有耗时操作

**Comment by MikeAfc** [comment]
也可以考虑下预加载，调用com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx#setRecycleOffset，参数就是需要预加载的高度，可以设置一屏高或者半屏高，设置之后，tangram会认为可见区域是屏高+offset，效果是提前bind，延后unbind
