### ISSUE TITLE
container-banner可以嵌套container-threeColumn吗

### ISSUE THREAD

**Issue by flyer1b** [alibaba/Tangram-Android#104]
![image](https://user-images.githubusercontent.com/11568049/39690364-6de688b2-520c-11e8-95e9-f6cec565b7ae.png)

**Comment by MikeAfc** [comment]
不可以，可使用组件实现，建议配合VirtualView的Grid实现http://tangram.pingguohe.net/docs/virtualview/grid
或自行实现Native View注册到Tangram。
