### ISSUE TITLE
由于TangramActivity在onDestroy释放ImageSetter错误再次进入导致IllegalStateException异常

### ISSUE THREAD

**Issue by 18337129968** [alibaba/Tangram-Android#106]
/**此处使用的是静态初始化sInitialized，却又在初始化接收设为true，没有考虑里面初始化的 ImageUtils.sImageClass被设空之后再次进入无法赋值导致IllegalStateException异常，4个Demo出现崩溃太多建议修复完善*/

 TangramBuilder.init(this.getApplicationContext(), new IInnerImageSetter() {
            @Override
            public <IMAGE extends ImageView> void doLoadImageUrl(@NonNull IMAGE view,
                    @Nullable String url) {
                Picasso.with(TangramActivity.this.getApplicationContext()).load(url).into(view);
            }
        }, ImageView.class);

  @Override
    protected void onDestroy() {
        super.onDestroy();
        if (engine != null) {
            engine.destroy();
        }
        ImageUtils.setImageSetter(null);//此处设空导致IllegalStateException异常
    }

**Comment by MikeAfc** [comment]
请仔细看 com.tmall.wireless.tangram.util.ImageUtils#setImageSetter 方法的参数，`@NonNull IInnerImageSetter imageSetter`，此方法期望接收非null参数
