### ISSUE TITLE
感谢阿里大神，解决了我最为头疼的复杂rv嵌套时，滑动卡顿加载缓慢的问题。

### ISSUE THREAD

**Issue by KomoriWu** [alibaba/Tangram-Android#108]
跟着demo一步步来，别放弃。刚开始看的我一脸蒙蔽

**Comment by flyer1b** [comment]
你是用container-scroll吗，我也有这个问题就是向左划越到后面，上下滑动的时候经过那个地方的时候卡顿越厉害

**Comment by KomoriWu** [comment]
@flyer1b 可以试试这个框架，但是引入module 之后apk 变大了10M左右。

**Comment by flyer1b** [comment]
我就是用这个框架的

**Comment by MikeAfc** [comment]
@KomoriWu Tangram + VirtualView + vlaout（246.48+261.06+186.49=694.3KB），这还是aar的大小，打包成apk要再除2的，增量是10M可以查查依赖了

**Comment by KomoriWu** [comment]
@MikeAfc 嗯嗯，谢谢大神。查出来了，是我的问题
