### ISSUE TITLE
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tmall/wireless/vaf/framework/VafContext;

### ISSUE THREAD

**Issue by KomoriWu** [alibaba/Tangram-Android#109]
按文档配置，变异不通过

**Comment by MikeAfc** [comment]
排查下gradle依赖

**Comment by KomoriWu** [comment]
文档上应该详细点，谢谢。
 //以下全部加上就行
    //tangram
    compile 'com.alibaba.android:tangram:3.1.0@aar'
    compile 'com.alibaba.android:vlayout:1.3.0@aar'
    compile 'com.alibaba.android:virtualview:1.3.0@aar'
    compile 'com.alibaba.android:ultraviewpager:1.0.6.9@aar'
    compile 'com.alibaba.android:virtual-common:1.0.9@jar'
