### ISSUE TITLE
container-banner 文档缺少属性

### ISSUE THREAD

**Issue by FishionMark** [alibaba/Tangram-Android#113]
http://tangram.pingguohe.net/docs/layout-support/pagescroll-layout    Banner类型的     文档属性缺少“itemRatio”  这个属性好像是必要的  没有的话如果Banner是在列表的第一个位置,那么展示的时候 会从banner下面开始展示   需要手动滑倒上面才可以看到banner

**Comment by MikeAfc** [comment]
文档已更新
