### ISSUE TITLE
初始化的时候遇到NoClassDefFoundError

### ISSUE THREAD

**Issue by princeHe** [alibaba/Tangram-Android#115]
07-07 21:57:14.068 4312-4312/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.he.demo, PID: 4312
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tmall/ultraviewpager/TimerHandler$TimerHandlerListener;
        at com.tmall.wireless.tangram.TangramBuilder.init(TangramBuilder.java:268)

**Comment by princeHe** [comment]
implementation 'com.alibaba.android:tangram:3.1.2@aar'
implementation 'io.reactivex.rxjava2:rxjava:2.1.13'
implementation 'io.reactivex.rxjava2:rxandroid:2.0.2'
这是gradle依赖配置，完全参照接入指南配置

**Comment by lizhw123** [comment]
文档上应该详细点，谢谢。
//以下全部加上就行

    implementation "com.alibaba.android:tangram:3.1.9.1@aar"
    implementation "com.alibaba.android:vlayout:1.2.18@aar"
    implementation "com.alibaba.android:ultraviewpager:1.0.7.7@aar"
    implementation "com.alibaba.android:virtualview:1.3.8.3@aar"
    implementation "com.alibaba.android:virtual-common:1.0.11@jar"
