### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tmall/wireless/tangram/view/BannerView;

### ISSUE THREAD

**Issue by DawningCheng** [alibaba/Tangram-Android#119]
今天尝试写个demo，发现用compile 'com.alibaba.android:tangram:3.1.2@aar'引入库运行会异常找不到类，直接引用源码就没这个问题

**Comment by MikeAfc** [comment]
参照# #118  依赖的时候不要加@aar，compile 'com.alibaba.android:tangram:3.1.2'
了解下@aar加和不加的区别
