### ISSUE TITLE
自定义view逻辑处理

### ISSUE THREAD

**Issue by maolubin** [alibaba/Tangram-Android#12]
public class TestView extends FrameLayout implements ITangramViewLifeCycle {
    private TextView textView;
    private BaseCell cell;

这种自定义view,在    @Override
    public void postBindView(BaseCell cell) {处理逻辑时，activity的上下文从哪传进来啊

**Comment by longerian** [comment]
拿到view的context其实就是Activity。如果觉得这样太隐患，可以在框架里通过serviceManager注册一个activity，然后在cell里通过serviceManager获取。参考获取SimpleClickSupport的方式
