### ISSUE TITLE
RecyclerView滑动时疯狂打印这些log，能不能去掉他们。

### ISSUE THREAD

**Issue by wt959790** [alibaba/Tangram-Android#126]
E/UiCodeLoader_TMTEST: getCode type invalide type
E/UiCodeLoader_TMTEST: getCode type invalide type
E/UiCodeLoader_TMTEST: getCode type invalide type
E/UiCodeLoader_TMTEST: getCode type invalide type
E/UiCodeLoader_TMTEST: getCode type invalide type
E/UiCodeLoader_TMTEST: getCode type invalide type
E/UiCodeLoader_TMTEST: getCode type invalide type
E/UiCodeLoader_TMTEST: getCode type invalide type
E/UiCodeLoader_TMTEST: getCode type invalide type
E/UiCodeLoader_TMTEST: getCode type invalide type
E/UiCodeLoader_TMTEST: getCode type invalide type
E/UiCodeLoader_TMTEST: getCode type invalide type
E/UiCodeLoader_TMTEST: getCode type invalide type
E/UiCodeLoader_TMTEST: getCode type invalide type

**Comment by MikeAfc** [comment]
收到，下周的release版本去掉

**Comment by zcm-hu** [comment]
I/Sticky: remainingSpace: 182    offset: 0       还有这个   添加了吸顶的布局后 不滑动也一直在打印这个
