### ISSUE TITLE
android ：type:container-scroll pageWidth 和 pageHeight 的单位是px 吗？

### ISSUE THREAD

**Issue by jiaqingrui** [alibaba/Tangram-Android#128]
android ：type:container-scroll pageWidth 和 pageHeight 的单位是px 吗？ 实现横向滚动

**Comment by MikeAfc** [comment]
是的

**Comment by MelonWXD** [comment]
> 是的

不是dp吗？
demo中第一个就是线性滚动的,高度明显不是100px啊..
```
"style": {
      "pageWidth": 200,
      "hGap": 100,
      "pageHeight": 100
    }
```

**Comment by MikeAfc** [comment]
我抽了。。是dp，另外还有rp单位，是根据屏幕比例适配的

Lewis Weng <notifications@github.com> 于2019年1月9日周三 上午10:31写道：
