### ISSUE TITLE
关于局部刷新的问题

### ISSUE THREAD

**Issue by maolubin** [alibaba/Tangram-Android#13]
比如我一开始加载了一份完整的json配置，中间几个组件因为逻辑我调接口，获取了新的图片路径和数据，我想更新这几个组件的图片和点击事件，能更新吗，大神，求解

**Comment by longerian** [comment]
这些逻辑就封装在组件内部好了

**Comment by maolubin** [comment]
@longerian  public void postBindView(BaseCell cell) {   这方法每次滚动都会调啊，调网络接口的话太频繁了，怎么处理的网络异步加载

**Comment by maolubin** [comment]
@longerian  大神怎么动态更新啊，求教育
