### ISSUE TITLE
请问tangram有没有相应的功能实现类似淘宝可以左右滑动带tab的viewpager吗，是使用container-banner和container-twoColumn嵌套吗？还是需要自己另外实现？有没有类似的代码例子可以提供参考？谢谢

### ISSUE THREAD

**Issue by githubforwork** [alibaba/Tangram-Android#138]
![screenshot_2019-01-02-01-04-45-836_com taobao taobao](https://user-images.githubusercontent.com/14049656/50574796-a1f34200-0e2a-11e9-8063-7863155d9f45.png)

**Comment by githubforwork** [comment]
@longerian 这个应该怎么解决？

**Comment by MelonWXD** [comment]
container-sticky 里边嵌套一个tablayout ，下边就自定义一个view添加滑动监听 。用busSupport实现 tab点击通知和下面的view左滑右滑的通知。

**Comment by longerian** [comment]
计划中，近几个月内会实现

**Comment by CCCCauchy** [comment]
这个需求现在实现了吗

**Comment by yushilong** [comment]
同问
