### ISSUE TITLE
关于配置的json

### ISSUE THREAD

**Issue by maolubin** [alibaba/Tangram-Android#14]
我配置了一个json，我想根据业务逻辑显示我需要显示的组件，忽略我不需要的组件，但我json是配置上去的，具体怎么办呢

**Comment by longerian** [comment]
这样子最好是通过代码动态生成配置。要不就是组件都解析出来，根据业务逻辑决定显示还是不显示。不管怎么样，都要有逻辑处理。

**Comment by maolubin** [comment]
@longerian 要不就是组件都解析出来，根据业务逻辑决定显示还是不显示  调哪个方法隐藏卡片组件

**Comment by longerian** [comment]
就是你在自定义view的postBindView里调用setVisiblility方法

**Comment by maolubin** [comment]
@longerian 整个卡片隐藏呢?

**Comment by longerian** [comment]
那就不行了，还是需要根据后台根据逻辑动态生成数据，这一块我们有工具配套的设施，不过目前还没开源出来，目前需要你们后端处理一下。

**Comment by maolubin** [comment]
就是你在自定义view的postBindView里调用setVisiblility方法  @longerian 不行啊，卡片还在啊

**Comment by longerian** [comment]
卡片必须动态改数据了

**Comment by maolubin** [comment]
@longerian 大神，postBindView 这个滚动会循环调，有参数控制调用次数吗

**Comment by longerian** [comment]
没有  这是组件生命周期的一部分
