### ISSUE TITLE
如果某个组件有红点，需要刷新这个组件

### ISSUE THREAD

**Issue by maolubin** [alibaba/Tangram-Android#15]
有方法指定这个组件用户无感知的刷新吗，还是要全部刷新一遍

**Comment by longerian** [comment]
如果是通过数据变化驱动界面刷新，可以用 `notifyItemChanged(position);` 方法；
如果是组件内部行为需要变化一下UI，直接在组件内部做就可以了。

**Comment by maolubin** [comment]
@longerian 数据变化指json文件内容变化？   组件内部的话，滑动会频繁调用绑定数据方法啊，还有组件是一直新建中吗，还是一直那一个对象

**Comment by maolubin** [comment]
@longerian 大神能更详细一点吗

**Comment by longerian** [comment]
数据变化就是说json变化了，  对于的basecell也变化了。

一个页面中数据是一个组件一个实例，但对应的view是会复用的。

**Comment by maolubin** [comment]
@longerian  json变了，用 notifyItemChanged(position);  就能刷新了？

**Comment by maolubin** [comment]
@longerian 大神，能加个QQ交流下吗

**Comment by longerian** [comment]
是的，局部数据变化刷新，就是普通使用recyclerView+Adapter的方式去刷新。
Tangram提供的接口是整体刷新、添加卡片、或者替换卡片这种批量的刷新。

**Comment by maolubin** [comment]
@longerian  我是这么刷的        Card card3 = engine.getGroupBasicAdapter().getGroups().get(3);
        List<BaseCell> cells = card3.getCells();
        for (int i = 0; i < cells.size(); i++) {
            ((TestViewHolderCell) cells.get(i)).setRedNum(i);
        }
        engine.refresh();

**Comment by longerian** [comment]
这样其实是整体刷新了一下，不过问题也不大。
