### ISSUE TITLE
只支持在Activity中使用吗？不支持Fragment？

### ISSUE THREAD

**Issue by matrixccp** [alibaba/Tangram-Android#150]

**Comment by matrixccp** [comment]
implementation 'com.alibaba.android:tangram:2.0.5@aar'
implementation 'com.alibaba.android:vlayout:1.3.0@aar'
implementation 'com.alibaba.android:virtualview:1.4.3@aar'
implementation 'com.alibaba.android:ultraviewpager:1.0.7.8@aar'
implementation 'com.alibaba.android:virtual-common:1.0.11@jar'

**Comment by QiaoYang0923** [comment]
您好,请问您找到结果了吗
