### ISSUE TITLE
大神，求助，滑动冲突问题

### ISSUE THREAD

**Issue by maolubin** [alibaba/Tangram-Android#16]
PtrClassicFrameLayout  外面加了这个下拉刷新的，发现有滑动冲突，求教你们怎么解决的，天猫用的也是这个吗 ，原生的RecyclerView是没冲突的

**Comment by longerian** [comment]
那是下拉刷新本身的问题吧  Tangram并不关心哪个RecyclerView

**Comment by maolubin** [comment]
@longerian 这个我解决了
