### ISSUE TITLE
建议灰度上线Tangram3

### ISSUE THREAD

**Issue by liufsd** [alibaba/Tangram-Android#161]
3.x版本似乎已经有很长一段时间了的，由于两个包都存在，所以无法接入验证，也不清楚具体怎么规划~

**Comment by MikeAfc** [comment]
近期会发布Tangram3.0的规划，Tangram3.0还处于开发阶段，正式上线可能在10月

liupeng <notifications@github.com> 于2019年5月28日周二 上午10:40写道：

**Comment by liufsd** [comment]
好的，期待

**Comment by shixiaolei** [comment]
@liufsd 您好 请问您的项目里用了3.x版本了吗？3.x是不是弃坑了==

**Comment by liufsd** [comment]
> @liufsd 您好 请问您的项目里用了3.x版本了吗？3.x是不是弃坑了==

https://github.com/alibaba/Tangram-Android/commit/9dbc326530c694c9673b2f747ce526836df4f88a
