### ISSUE TITLE
刷新问题：replaceData方法替换卡片数据是只替换卡片，还是包含了卡片和卡片里的组件

### ISSUE THREAD

**Issue by maolubin** [alibaba/Tangram-Android#18]
public void replaceData(int position, @Nullable T data)  替换卡片数据是只替换卡片，还是包含了卡片和卡片里的组件

**Comment by maolubin** [comment]
TangramEngine 里面的方法
添加卡片数据

public void insertData(int position, @Nullable T data)
插入卡片数据

public void replaceData(int position, @Nullable T data)
替换卡片数据

上述几个方法都有原始json 数据类型和解析过的卡片 model 数据类型的版本。

**Comment by longerian** [comment]
第一个问题，——答：替换卡片+卡片里组件的数据
