### ISSUE TITLE
Android :吸顶布局里面的offset属性没有用

### ISSUE THREAD

**Issue by wht0707** [alibaba/Tangram-Android#22]
我在库里面的StickyCard类里面发现
StickyLayoutHelper里面的helper.setOffset(); 这个方法没有调用.
Style类中也没有定义offset的属性和赋值.
我尝试着仿照bgColor属性写法,重新给offset定义和赋值,发现运行起来offset是生效的。

**Comment by longerian** [comment]
StickyLayoutHelper 是更通用的逻辑，设计了一些tangram里可能不需要的额外属性，像这个offset，就没有强加到tangram体系里配置。

**Comment by wht0707** [comment]
明白了,谢谢。
