### ISSUE TITLE
有关下拉刷新兼容的的问题

### ISSUE THREAD

**Issue by wht0707** [alibaba/Tangram-Android#23]
在使用中发现对github上很多的第三方刷新控件兼容不够好。第三方的下拉时触发不了刷新的操作,只能通过代码触发,目前发现可用的是SwipeRefreshLayout或者自定义SwipeRefreshLayout的一些能够使用。

**Comment by longerian** [comment]
是的 这一块还没有针对每一个下拉刷新控件调过。
