### ISSUE TITLE
StickyCard与StaggeredCard滑动冲突

### ISSUE THREAD

**Issue by wht0707** [alibaba/Tangram-Android#25]
在使用中StickyCard如果在StaggeredCard上面,在页面滑动时会闪。
我现在的处理方法是:在两个布局中间加一个SingleColumnCard布局,
高度设置的很小,这样能间接的解决。

**Comment by longerian** [comment]
是的  底层vlayout有个bug，在vlayout1.0.9里解决了这个问题。更新一下Tangram对vlayout的依赖即可。
