### ISSUE TITLE
吸顶布局为啥有外边距，明明设为0了啊

### ISSUE THREAD

**Issue by maolubin** [alibaba/Tangram-Android#26]
{
    "type": 20,
    "style": {
      "sticky": "start",
      "offset": 20,
      "margin": [
        0,
        0,
        0,
        0
      ],
      "padding": [
        0,
        0,
        0,
        0
      ]
    },
    "items": [
      {
        "type": 8,
        "msg": "sticky"
      }
    ]
  },

**Comment by maolubin** [comment]
关了把，解决了

**Comment by linyouzhen124** [comment]
您好，我目前使用也碰到这个问题，看demo中也是有这个问题，请问是怎么解决的呢？谢谢
