### ISSUE TITLE
是不是不更新啦?

### ISSUE THREAD

**Issue by yaming116** [alibaba/Tangram-Android#28]

**Comment by longerian** [comment]
感谢你的关注，不好意思给你带来这样的疑惑，事实上我们有一定的迭代节奏，大致流程是新特性在内部版本开发完之后，落地到业务中检验成熟之后再开放。
目前内部版本的代码远远领先于开源版本，无论是组件的模型还是组件的开发方式，但是还未经过充分的实战检验之前，我们认为还不具备开放的条件，所以没有对已开源版本做大更新，到是底层vlayout有较多bugfix的改动。

**Comment by yaming116** [comment]
目前得到的回复都是统一答案,内部版本没有验证,但是时间已经过去好几个月了,不知道是否有稍稍具体一点的日期,目前的情况来说,只能观望当前的项目.

**Comment by longerian** [comment]
我们会再讨论个具体的时间点出来再发出来，更新策略也会发出来。

**Comment by longerian** [comment]
后续的安排贴在这里：http://tangram.pingguohe.net/docs/roadmap/

**Comment by longerian** [comment]
@yaming116  抱歉，确实来得很晚，但是开源是个严肃的事情，我们有很多流程要走，有很多东西要准备，就像上线一个产品一样，尽管还不算尽善尽美，但也把大部分东西都放出来了。
参考：http://pingguohe.net/2017/12/07/Tangram-2.html

**Comment by yaming116** [comment]
已经看到了，感谢你们开源出来的产品。
