### ISSUE TITLE
能介绍的更加详细吗

### ISSUE THREAD

**Issue by maolubin** [alibaba/Tangram-Android#34]
// built-in mCells
        registry.registerCell(TYPE_EXTENDED_VIEW, Card.PlaceholderCell.class,
                SimpleEmptyView.class);
        registry.registerCell(TYPE_EMPTY_VIEW, BaseCell.class, SimpleEmptyView.class);
        registry.registerCell(TYPE_CAROUSEL_CELL, BannerView.class);
        registry.registerCell(TYPE_SINGLE_COLUMN_ENTITY, GridEntityCardView.class);
        registry.registerCell(TYPE_DOUBLE_COLUMN_ENTITY, GridEntityCardView.class);
        registry.registerCell(TYPE_TRIPLE_COLUMN_ENTITY, GridEntityCardView.class);
        registry.registerCell(TYPE_FOUR_COLUMN_ENTITY, GridEntityCardView.class);
        registry.registerCell(TYPE_FIVE_COLUMN_ENTITY, GridEntityCardView.class);
        registry.registerCell(TYPE_CAROUSEL_ENTITY, BannerView.class);

        registry.registerCell(TYPE_LINEAR_SCROLL_CELL, LinearScrollView.class);

        // built-in cards
        registry.registerCard(TYPE_CAROUSEL, BannerCard.class);
        registry.registerCard(TYPE_SINGLE_COLUMN, SingleColumnCard.class);
        registry.registerCard(TYPE_DOUBLE_COLUMN, DoubleColumnCard.class);
        registry.registerCard(TYPE_TRIPLE_COLUMN, TripleColumnCard.class);
        registry.registerCard(TYPE_FOUR_COLUMN, FourColumnCard.class);
        registry.registerCard(TYPE_ONE_PLUS_N, OnePlusNCard.class);
        registry.registerCard(TYPE_FLOAT, FloatCard.class);
        registry.registerCard(TYPE_PIN_BOTTOM, PinBottomCard.class);
        registry.registerCard(TYPE_FIVE_COLUMN, FiveColumnCard.class);
        registry.registerCard(TYPE_STICKY, StickyCard.class);
        registry.registerCard(TYPE_STICKY_START, StickyCard.class);
        registry.registerCard(TYPE_STICKY_END, StickyEndCard.class);
        registry.registerCard(TYPE_PIN_TOP, PinTopCard.class);
        registry.registerCard(TYPE_STAGGER, StaggeredCard.class);

        registry.registerCard(TYPE_FUSION_TABS, FusionCard.class);
        registry.registerCard(TYPE_FLOW, FlowCard.class);
        registry.registerCard(TYPE_SCROLL_FIX, ScrollFixCard.class);

        registry.registerCard(TYPE_LINEAR_SCROLL, LinearScrollCard.class);
        registry.registerCard(TYPE_SCROLL_FIX_BANNER, FixLinearScrollCard.class);

        // extend cards
        registry.registerCard(TYPE_FIX, FixCard.class);
        registry.registerCard(TYPE_GRID, GridCard.class);
        registry.registerCard(TYPE_LINEAR, LinearCard.class);
        registry.registerCard(TYPE_X_COLUMN, ColumnCard.class);

**Comment by longerian** [comment]
这些是注册内置的组件和布局类型，使用时不用关心。

**Comment by maolubin** [comment]
@longerian 话说后面几个具体是什么卡片，文档没写，不大清楚

**Comment by longerian** [comment]
http://tangram.pingguohe.net/docs/layout-support/inner-support   这个文档看过没，在用的都在这里。

**Comment by maolubin** [comment]
看了，可是好多style字段好像没写，还有 registry.registerCard(TYPE_FUSION_TABS, FusionCard.class);
    registry.registerCard(TYPE_FLOW, FlowCard.class);
    registry.registerCard(TYPE_SCROLL_FIX, ScrollFixCard.class);

    registry.registerCard(TYPE_LINEAR_SCROLL, LinearScrollCard.class);
    registry.registerCard(TYPE_SCROLL_FIX_BANNER, FixLinearScrollCard.class);

    // extend cards
    registry.registerCard(TYPE_FIX, FixCard.class);
    registry.registerCard(TYPE_GRID, GridCard.class);
    registry.registerCard(TYPE_LINEAR, LinearCard.class);
    registry.registerCard(TYPE_X_COLUMN, ColumnCard.class);这几个，文档没提到

**Comment by longerian** [comment]
TYPE_FLOW = 27, 流式布局:http://tangram.pingguohe.net/docs/layout-support/flow-layout
TYPE_SCROLL_FIX = 28，也是固定的，但是可配置showType(滚动到某个布局的时候，出现并固定)， ：http://tangram.pingguohe.net/docs/layout-support/fix-layout

TYPE_LINEAR_SCROLL：就是一个横向的recyclerview的效果
TYPE_SCROLL_FIX_BANNER：就是横向recycleerview+fix的效果，可悬浮

剩下几个都是以上的通用设计，没有直接使用，可忽略。

**Comment by maolubin** [comment]
有使用这些新的demo吗

**Comment by longerian** [comment]
demo 没有覆盖到每一个点
