### ISSUE TITLE
组件相关问题

### ISSUE THREAD

**Issue by DukeLee1989** [alibaba/Tangram-Android#36]
1.请问组件开发规范的文档在哪里，点击链接跳转地址不对呢。
2.如果组件里面控件的size，margin修改了，要两端不用发版动态变化，怎么做？

**Comment by longerian** [comment]
1. 文档 ：http://tangram.pingguohe.net/docs/basic-concept/history  通过这个找，哪个地址不对，
2. 组件里的margin可以配置，不用发版，控件的size，目前是需要发版的，动态化方案还在待开源流程里。

**Comment by longerian** [comment]
@DukeLee1989 做动态化组件的方案，我们上周也开放出来了。阅读此文大概了解一下先。
