### ISSUE TITLE
BannerCard问题

### ISSUE THREAD

**Issue by ZQ7** [alibaba/Tangram-Android#37]
同一页面,有一个轮播图(自动滚动的),有一个横向滑动的布局，横向布局也会自动滚动,求解

**Comment by longerian** [comment]
『有一个横向滑动的布局』  是怎么样的？配置如何？

**Comment by ZQ7** [comment]
@longerian http://tangram.pingguohe.net/docs/layout-support/pagescroll-layout
同一页面用了两个轮播，第一个设置自动滚动的间隔后，第二个没有任何设置就会随着第一个的滚动间隔滚动，目前解决方法是给第二个设置了一个很大的时间间隔(目的是不想让第二个卡片内的Cell滚动)

**Comment by longerian** [comment]
复用的时候有个bug，#73 里解决了。
