### ISSUE TITLE
关于部分卡片（组件）会划出recyclerView的问题

### ISSUE THREAD

**Issue by clayx** [alibaba/Tangram-Android#39]
如果在布局文件中，在RecyclerView上方空出一段区域，那么在滑动过程中，如TYPE_FOUR_COLUMN卡片中有多个组件（12个），那么快速滑动，可能会出现上方空出来的区域，也会显示划出的组件中的图片。
![](http://i2.bvimg.com/610123/e06cbbdb57480bc1.png)

个人定位问题：在滑动过程中，组件中的相关的View已经释放掉了，但是图片未释放掉。
求助：碰到这种问题，应该怎么处理，因为在相关项目中，在RecyclerView上方存在相关Indicator，而在相关的json数据中用到相关的TYPE_FOUR_COLUMN的卡片，会出现这种情况。

**Comment by longerian** [comment]
图片看不到

**Comment by clayx** [comment]
直接打开好像打不开，复制连接到浏览器打开

**Comment by longerian** [comment]
布局文件怎么写？『么快速滑动，可能会出现上方空出来的区域』怎么理解，recyclerView的内容出现在它容器的外部？

**Comment by clayx** [comment]
布局文件如下，只是在RecylerView上加了一个TopMargin= 30dp;
『么快速滑动，可能会出现上方空出来的区域』就是在快速滑动的时候，可能这个组件中的图片会出现在上方的空白区域，即这个marginTop的区域。

`<?xml version="1.0" encoding="utf-8"?>


<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             android:layout_width="match_parent"
             android:layout_height="match_parent"
             android:background="@color/xiu_page_bg">


    <android.support.v7.widget.RecyclerView
        android:id="@+id/main_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/xiu_page_bg"
        android:layout_marginTop="30dp"
        android:paddingLeft="0dp"
        android:paddingRight="0dp"
        android:requiresFadingEdge="none"
        android:scrollbars="vertical">

    </android.support.v7.widget.RecyclerView>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|center">

        <TextView
            android:id="@+id/first"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:text="First"/>

        <TextView
            android:id="@+id/last"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:text="Last"/>

        <TextView
            android:id="@+id/count"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"/>
    </LinearLayout>
</FrameLayout>`

**Comment by clayx** [comment]
[http://i4.bvimg.com/610123/d96aebafbc4ec09d.png](正常显示)

**Comment by longerian** [comment]
出现错误的时候，你用布局检测工具跑一下，看看recyclerView的范围还对不对，布局到容器外部的view是看不到的，如果你看到了，很可能是recyclerView自己的区域已经变了。

**Comment by clayx** [comment]
我用的是手机系统的布局查看器，当划过的时候，图片是出去了，但是布局的区域并没有改变。

**Comment by longerian** [comment]
你看看有没有什么异常抛出来，加margin不至于出现这种错误。

**Comment by clayx** [comment]
没有抓到异常，重新使用框架新开一个项目，然后进行测试，不会出现问题，感觉是我们这边有人修改了源码导致的，感谢@longerian及时回答问题，我再去排查下导致问题的原因，非常感谢。
