### ISSUE TITLE
按照文档接入引用出错

### ISSUE THREAD

**Issue by nuoxiang** [alibaba/Tangram-Android#4]
使用compile 'com.tmall.android:tangram:1.0.0@aar'时提示 Failed to resolve: com.tmall.android:tangram:1.0.0

apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "think.tangramdemo"
        minSdkVersion 14
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.1.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha9'
    testCompile 'junit:junit:4.12'
    compile 'com.tmall.android:tangram:1.0.0@aar'
}
以上是build.gradle中的配置

**Comment by MikeAfc** [comment]
使用这个坐标 compile 'com.alibaba.android:tangram:1.0.0@aar'

**Comment by longerian** [comment]
把文档更新一下

**Comment by nuoxiang** [comment]
问题解决了 Tks
