### ISSUE TITLE
Tangram V2.0 具体说明时候发布呢？

### ISSUE THREAD

**Issue by liufsd** [alibaba/Tangram-Android#40]
您好，非常感谢开源Android和ios客户端整体解决方案，非常赞，看到你们说明里面有写到，打算2.0重构。请问具体什么时候发布呢？或者给一个snapshot包呢？
个人比较担心2.0与1.0差异比较多。所以希望直接上手2.0.
另外发现Android 和 ios 项目最近三个月都没有提交代码了的。
还有，发现开源之后，issue里面提的问题还是很多的，但欣慰的是，你们解决非常迅速。
再次感谢。
希望给予时间安排答复。

**Comment by longerian** [comment]
感谢你的关注，之前承诺8月份会放出来，目前在准备流程中，时间仓促，2.0开放出来也会有一些不完善的地方，主要是周边设施，文档。在代码放出来之后会转移到github上持续更新。

**Comment by liufsd** [comment]
感谢您的回复，大概最快是什么时候发布呢？

**Comment by longerian** [comment]
大概要一周时间，先开放Android的。

**Comment by liufsd** [comment]
wow~ 赞 非常感谢。
期待。
另外一点点个人愚见，可以把README完善一下，发现issue里面很多问题可能是因为使用方式细节上的不清楚导致的。
再次感谢。

**Comment by longerian** [comment]
嗯  你看过http://tangram.pingguohe.net/  http://pingguohe.net/ 这里的文档吗，README可能比较简单，我们整理一下，把相关内容收集到一起。

**Comment by liufsd** [comment]
恩  我就是看了你们的文档，已经挺详细了的，

**Comment by liufsd** [comment]
您好，（https://github.com/alibaba/Tangram-Android/issues/28）看到有人说更新安排在这里： http://tangram.pingguohe.net/docs/roadmap/ 上面写的是30号出2.0版本，但前几天这里，您说最快一周就可以出来了的。
刚也抽空写了一下，感觉很赞。
但还是期待2.0还是更加期待，因为您在那个issue里面提到说开发方式会更加清爽。
所以希望正式接入项目的时候，上手2.0.
感谢。

**Comment by longerian** [comment]
你好，感谢关注。目前我们已经提交申请，已经在公司的开源审批流程里了。但是流程比预期的要长很多，没有办法快速放出，这一点可能要让你失望了。😂 😂 😂

**Comment by liufsd** [comment]
啊，API变化大么?最快多久？

**Comment by longerian** [comment]
API 变化不大，会新增一些。时间现在不好确定..... 😥 😥

**Comment by liufsd** [comment]
好，希望尽快给出，期待。但还是求稳吧。

**Comment by sanvibyfish** [comment]
顺带问一下，json的文档在哪可以找到
