### ISSUE TITLE
按文档配置，编译报错

### ISSUE THREAD

**Issue by primewang** [alibaba/Tangram-Android#41]
配了这个compile 'com.alibaba.android:tangram:1.0.0@aar'
报Failed resolution of: Lcom/alibaba/android/vlayout/VirtualLayoutManager错误，
是还要配置
 compile('com.alibaba.android:vlayout:1.0.3@aar') 
这个吗?

**Comment by niulinguo** [comment]
// RecyclerView依赖
    // alibaba/Tangram-Android
    compile 'com.alibaba.android:tangram:1.0.0@aar'
    // alibaba/vlayout
    compile ('com.alibaba.android:vlayout:1.2.0@aar') {
        transitive = true
    }
    // alibaba/UltraViewPager
    compile ('com.alibaba.android:ultraviewpager:1.0.6@aar') {
        transitive = true
    }


我都加上了，编译通过

**Comment by longerian** [comment]
参考 @niulinguo
