### ISSUE TITLE
loadmore 如何实现在列表底部显示加载loading？

### ISSUE THREAD

**Issue by liufsd** [alibaba/Tangram-Android#42]
分页加载，是否可以在底部显示一个cell呢？

1.比如加载失败后，‘点击重试’
2. 或者网络比较慢，请求还没有回来，底部显示'loading.'

看了下，demo中，有在json里面配置

{
"type": "1",
"load": "com.tmall.request.load.more",
"loadType": 1,
"items": [
]
}
然后代码里面通过 AsyncPageLoader 去加载数据。但是界面上并没有显示'loading'的这个cell，因为它其实是一个‘card’，items为空，所以没有显示在界面上，等数据加载完，直接显示了新增的数据。

如果我需要实现正常的分页加载效果，如何处理比较好呢？
谢谢。

**Comment by liufsd** [comment]
这里有分页加载的说明，但是未提到在最底部显示一个占位的加载视图。而底部显示‘loading/retry’视图，还是比较常见的。不知道框架中，是否有对应的实现方案呢？
https://github.com/pingguohe/tangram/blob/bcbe8ba4893a85e9a55cc2df1ca302eba0dfe14b/_docs/android/load-data.md

**Comment by longerian** [comment]
分页，我们现在考虑了一下，建议在页面级别去做，也就是recyclerView自己监听滑动到底部，做loading的ui显示，然后拉倒新的数据追加到页面末尾。

card里的loading配置的接口只用来一次性加载自己内部的数据。

**Comment by liufsd** [comment]
ok，好的。感谢您的回复。这个确实是可以自己实现的。
