### ISSUE TITLE
页面快速滑动时有重影

### ISSUE THREAD

**Issue by wht0707** [alibaba/Tangram-Android#47]
![849f1a3126e089578db56e01f66e7396](https://user-images.githubusercontent.com/26018016/30813415-f85b1558-a23f-11e7-8eff-3d8f97798f8d.jpg)
我的首页是类似购物的首页,上面有许多图片,但是我在快速滑动的时候就会出现图片上的重影问题,
我现在不知道哪里出现了问题?,希望您能看一下

**Comment by longerian** [comment]
根据之前的反馈，是图片库的问题。看看你使用的是什么图片库

**Comment by wht0707** [comment]
Glide

**Comment by longerian** [comment]
Glide 内部机制还没研究过，可能是和它加载图片做动画有关。 目前反馈来看用Picasso是ok的。

**Comment by wht0707** [comment]
好的,谢谢了
