### ISSUE TITLE
忍不住了，有个疑问，望能解惑。关于 BaseCell 中数据操作的。

### ISSUE THREAD

**Issue by hetianpeng** [alibaba/Tangram-Android#48]
在 BaseCell 类中的 bindView() 方法里，有很多条数据需要展示，而这些数据都在一个 BaseCell 中的JSONObject 类型的变量中存储。

数据过多，使用 optJsonObjectParam() 等等一系列方法，去一个个取数据，写起来真的挺麻烦的。

我是否能够在 bindView() 中去这样操作 new Gson().fromJson() ?

怕这样写会造成性能差，但是 optXXX() 很多数据时，真的很烦人。

**Comment by longerian** [comment]
尽量不要new对象，取数据是难以避免的，不在bindView里取，也是要在另外一个地方取。

我们提供了自动绑定数据的方式，但是需要用到反射调用，会影响性能所以不建议使用。在 http://tangram.pingguohe.net/docs/android/develop-component  组件开发模式二里有说明

**Comment by hetianpeng** [comment]
谢谢，了解了。
