### ISSUE TITLE
2.0版本是又推后了吗

### ISSUE THREAD

**Issue by duantao561** [alibaba/Tangram-Android#49]

**Comment by longerian** [comment]
已经在流程里，恰逢双十一，还有一些材料要准备，比较慢。

**Comment by liufsd** [comment]
尴尬啊
“已经在流程里，恰逢双十一，还有一些材料要准备，比较慢。”

大概是什么时候呢？

**Comment by longerian** [comment]
@duantao561 
抱歉，各位，确实来得很晚，但是开源是个严肃的事情，我们有很多流程要走，有很多东西要准备，就像上线一个产品一样，尽管还不算尽善尽美，但也把大部分东西都放出来了。
参考：http://pingguohe.net/2017/12/07/Tangram-2.html
