### ISSUE TITLE
横向滚动布局布局Bug

### ISSUE THREAD

**Issue by ZQ7** [alibaba/Tangram-Android#50]
"type": "10",
"pageRatio": 0.33,
items<3(即横向item的view不足一屏)时向右滑动会闪屏，求解决方式

**Comment by zoomself** [comment]
可以判断下当前items的个数，动态设置type,如果少于你设想的一屏显示数量，比如你要的3个，可以选用type:3,即3列的布局，超出了则用type:10就不会出现闪屏现象了
