### ISSUE TITLE
关于混淆的问题

### ISSUE THREAD

**Issue by Einsteinford** [alibaba/Tangram-Android#51]
请问除了在proguard-rules.pro中添加以下语句，还应该添加哪些来保证运行时不会报错呢
`-keep class com.tmall.** { *;}
-keep class me.everything.** { *;}
-dontwarn com.tmall.**`

**Comment by Einsteinford** [comment]
似乎，再加上
`-keep class com.alibaba.** { *;}
`
然后是所有注册的组件(builder.registerCell(int type,  Class<V> view))
`-keep class com.（伪代码）.view.tangram.** { *;}
`

**Comment by wht0707** [comment]
请问你解决了混淆问题吗?

**Comment by wht0707** [comment]
#-----------vlayout
 -keepattributes InnerClasses
 -keep class com.alibaba.android.vlayout.ExposeLinearLayoutManagerEx { *; }
 -keep class android.support.v7.widget.RecyclerView$LayoutParams { *; }
 -keep class android.support.v7.widget.RecyclerView$ViewHolder { *; }
 -keep class android.support.v7.widget.ChildHelper { *; }
 -keep class android.support.v7.widget.ChildHelper$Bucket { *; }
 -keep class android.support.v7.widget.RecyclerView$LayoutManager { *; }
我的加上这个就好了
