### ISSUE TITLE
这个框架是阿里天猫开源的吗

### ISSUE THREAD

**Issue by maolubin** [alibaba/Tangram-Android#53]
我们用它，没有版权问题把

**Comment by gaosboy** [comment]
是天猫开源的，你可以用，遵循协议就好

**Comment by maolubin** [comment]
哥，我领导让我证明是来自天猫的，是开源的，有没有明确的地方或来源能证明是天猫开源的呢，谢谢了

**Comment by Einsteinford** [comment]
查看Code里的MIT License，这是个宽松型开源协议，随便用，不会有侵权赔偿，最多告你不准用而已
