### ISSUE TITLE
原有的项目数据规则不一致，要如何改造？

### ISSUE THREAD

**Issue by imagec** [alibaba/Tangram-Android#56]
对页面的描述要按照要求的json来描述，这样如果服务端的数据就是同样的格式就很方便，而如果不同，做一次转换，感觉还是有点麻烦的了。有什么建议？

**Comment by longerian** [comment]
我们也是在后端转换数据的，有一个配套的服务，争取早日开放出来配合使用

**Comment by longerian** [comment]
另外可以给后端写一个简单的sdk，按照 Tangram 对数据的要求写出基础model，提供set get方法，再提供类似于一个render的方法，让他能吐出Tangram结构的数据即可，让后端不用关心具体细节，这一块也在规划里，争取早日开放。http://pingguohe.net/2017/12/07/Tangram-2.html
