### ISSUE TITLE
可以配合那些下拉刷新，上拉加载的控件使用。

### ISSUE THREAD

**Issue by imagec** [alibaba/Tangram-Android#57]
貌似该框架不支持下拉刷新和上拉加载吧？有其他组件推荐配合使用吗?

**Comment by longerian** [comment]
这个框架需要用户提供一个recyclerView，至于recyclerView和下拉刷刷新框架的配合，这个是不干预的。

**Comment by longerian** [comment]
推荐使用 https://github.com/scwang90/SmartRefreshLayout 这个吧。
