### ISSUE TITLE
项目还更新吗？

### ISSUE THREAD

**Issue by ZQ7** [alibaba/Tangram-Android#58]

**Comment by longerian** [comment]
预计还有半个多月就更新一把

**Comment by liufsd** [comment]
期待啊~。~ 
虽然还要半个月。。。

**Comment by longerian** [comment]
模型的定义、概念更新了下，页面结构也升级过，最主要的是新增了一种动态化制作view的方案。

**Comment by liufsd** [comment]
wow~
希望这次界面可以更加流畅~
期待。
最快什么时候能给出来呢？
我预计下个礼拜就要开始动工了的。

**Comment by yanyusong** [comment]
Tangram 现在都主要用在阿里的哪些产品和模块上？0.0

**Comment by liufsd** [comment]
半个月过去了的~。~
进展怎么了呢？ @longerian

**Comment by longerian** [comment]
@liufsd  流程基本通过，下周就放出来。
@yanyusong 在天猫、阿里星球、aliexpress有使用。新的方案下周有更新。

**Comment by liufsd** [comment]
wow, 希望这次，礼拜一礼拜二能看到啊。
期待
赞👍
感谢、

**Comment by liufsd** [comment]
@longerian  看到这几天你在维护代码，感觉明天能收到期待已久的2.0版本哦。
辛苦啦。
非常感谢。

**Comment by longerian** [comment]
是的，快了，已经准备好了，在等iOS端的审批通过，一起同步放。

**Comment by liufsd** [comment]
今天不能发布嘛？

**Comment by longerian** [comment]
讨论了下，还是要一起发，稍安勿躁，已经就差最后一个环节了。

**Comment by liufsd** [comment]
哈哈哈  好的

**Comment by liufsd** [comment]
@longerian   hello~ 进展如何了呢？今天可以发布吗？

**Comment by longerian** [comment]
可以的   正在搞

**Comment by liufsd** [comment]
👍👏👍

**Comment by longerian** [comment]
抱歉，各位，确实来得很晚，但是开源是个严肃的事情，我们有很多流程要走，有很多东西要准备，就像上线一个产品一样，尽管还不算尽善尽美，但也把大部分东西都放出来了。
参考：http://pingguohe.net/2017/12/07/Tangram-2.html
