### ISSUE TITLE
BannerCard怎么添加header

### ISSUE THREAD

**Issue by kanliuzuoyou** [alibaba/Tangram-Android#59]
bannerCard 怎么增加header

**Comment by longerian** [comment]
加个就可以了，比如：
```
"header": {
						"subTitle": "副标题",
						"title": "标题",
						"type": "hot-channel-header"
					}
```

**Comment by kanliuzuoyou** [comment]
我是想把header指向某一个组件，没有成功，你这里hot-channel-header是指什么呢

**Comment by kanliuzuoyou** [comment]
增加header是在1.0上就可以生效吗。

**Comment by liufsd** [comment]
@kanliuzuoyou  1.0 2.0 都支持

**Comment by kanliuzuoyou** [comment]
我用这种方法不显示，能是什么原因吗

**Comment by longerian** [comment]
@kanliuzuoyou  『type』是我随便起的一个名字，就是每个组件都要有个类型，header也是一个组件，所以写个type。

**Comment by kanliuzuoyou** [comment]
![image](https://user-images.githubusercontent.com/33275341/33757332-ade84692-dc34-11e7-9b42-7e4b0141b62f.png)
如果是这样的界面我考虑用Tangram里面的FlowCard，但是貌似这个是不支持header，我刚开始看这个，能给点意见吗

**Comment by liufsd** [comment]
@kanliuzuoyou 给你个小小的建议：
你可以多看看源代码：https://github.com/alibaba/Tangram-Android/blob/master/tangram/src/main/java/com/tmall/wireless/tangram/structure/card/FlowCard.java

他们都是基于Card去扩展的: https://github.com/alibaba/Tangram-Android/blob/master/tangram/src/main/java/com/tmall/wireless/tangram/dataparser/concrete/Card.java
Card本身就是带头和底部的，只是具体实现是交给子类去扩展实现的。
```
     protected void parseHeaderCell(@NonNull MVHelper resolver, @Nullable JSONObject header) {

    }

    protected void parseFooterCell(@NonNull MVHelper resolver, @Nullable JSONObject footer) {

    }
```

**Comment by longerian** [comment]
@kanliuzuoyou flowCard 是支持header的，
@liufsd 非常给力，看来你也要精通 Tangram 的原理了。

**Comment by kanliuzuoyou** [comment]
谢谢回复，后来看了代码，有一个静态代码需要加上支持header的type，之后解决了
