### ISSUE TITLE
图片重置的问题

### ISSUE THREAD

**Issue by kanliuzuoyou** [alibaba/Tangram-Android#62]
下滑一段之后再滑回，发现图片闪烁重置，banner回到第一张，这个问题怎么处理

**Comment by longerian** [comment]
我处理一下，试着内部记录一下状态值吧

**Comment by kanliuzuoyou** [comment]
图片也会有进入到placeholder的reload的情况

**Comment by kanliuzuoyou** [comment]
是同一组件导致内存释放和复用引起的吗

**Comment by kanliuzuoyou** [comment]
这个问题可以有没有合适的解决方式啊，有这个问题，我不能投入使用啊

**Comment by kanliuzuoyou** [comment]
有办法处理这个问题吗

**Comment by longerian** [comment]
图片是复用的，是要重新加载一下的

**Comment by kanliuzuoyou** [comment]
我们有技术交流群吗，以后问题多了可以互助

**Comment by kanliuzuoyou** [comment]
图片的问题我已经解决了，但是banner回到第一张的问题不清楚怎么解决

**Comment by longerian** [comment]
@kanliuzuoyou  技术交流群我在准备，大概本周内会提供出来。

banner回到第一张的问题，在banner内部记录一下状态就好了，本周解决。

**Comment by kanliuzuoyou** [comment]
还有一个问题，BannerCard设置了pageWidth也不会起作用，不会变成线性的滑动，估计是因为空间是viewpager的原因，那这种如果使用内置Card是不是只能使用LinearScrollCard了

**Comment by longerian** [comment]
是啊  viewpager不是线性的

**Comment by longerian** [comment]
刚刚聊了一下，开群很容易导致画风不对，我们以issues为主交流，这样重复问题能整理，有沉淀，我们会保持对issue的关注的。

**Comment by longerian** [comment]
@kanliuzuoyou  我建群了。   到readme 那里搜索我的帐号，获取邀请
