### ISSUE TITLE
能不能开放PojoDataParser部分给我们呢？

### ISSUE THREAD

**Issue by liufsd** [alibaba/Tangram-Android#65]
问题是这样的：由于我们后端数据，和七巧板要求的数据格式不同，那么需要中间转换，想了下，如果我们能干预一下解析，直接返回card，这样只需要解析一次就够了的，缺点是card可能不能复用了的（比如style什么的数据字段都无法提供给之前的card），需要手动写一下card的子类等。
否则，只能中间做一个covert，然后吐出来sdk要求的json格式，然后再晒给sdk进行解析和渲染。
这样兼容性是个问题，比如如果七巧板SDK字段发生了变更，就不行了的。

```
  TangramEngine tangramEngine =
                new TangramEngine(mContext, new PojoDataParser(), mPojoAdapterBuilder);

```
如果您们觉得可以的话，我也可以提供支持。

**Comment by liufsd** [comment]
像ios端那样，有一个类似 `TangramDefaultDataSourceHelper`
```
    self.layoutArray = [TangramDefaultDataSourceHelper layoutsWithArray:self.layoutModelArray tangramBus:self.tangramBus];

```

`layoutArray`是直接返回card数组，然后进行数据渲染，那么我们就可以自己实现我们的业务处理的`TangramDataSourceHelper`了的。

是否可行呢？

**Comment by liufsd** [comment]
@longerian  你有什么好的建议么？关于json数据格式问题。
ios 也有人咨询这个问题。
https://github.com/alibaba/Tangram-iOS/issues/32

**Comment by longerian** [comment]
你调用 `BaseTangramEngine` 的 `parseComponent` 或  `parseData`   就是直接返回cell数组 或者 card  应该就是你要的方式。

**Comment by longerian** [comment]
数据格式我们就是在后端转换的，当然这个配套的服务目前还不具备对外开放的能力。
后端可以写一个简单的sdk，提供tangram组件的pojo类，提供set、get方法，然后调用一下转换器的方法直接输出tangram要求的json格式。

**Comment by liufsd** [comment]
不是，‘ parseData’ 我是没法干预了的已经。因为没开放出来哦。

**Comment by longerian** [comment]
ok，我在Builder加一下接口，允许你注册自己的DataParser

**Comment by liufsd** [comment]
对，所以你支持像ios那样，可以手动干预解析数据啦？ 
哈哈哈，赞。这样只需要解析一次就可以了的。后面渲染逻辑，依旧沿用SDK里面的渲染逻辑。
不过我在思考，这样解析，由于card这个数据结构，需要一些类似样式style配置，如果自己解析的话，可能缺少字段，会不会有crash问题呢？比如SDK内部取数据的时候，null的问题。

**Comment by liufsd** [comment]
1. 接入方自己转换，然后丢tangram的数据是，按照tangram的数据结构来。优点是：完全符合tangram数据结构。缺点是：转换的时候，由于接入方下发的一般都是比较业务的具体数据值，而缺少样式相关的配置，而tangram需要。所以需要手动补全json数据，需要写死字段名称等，后期和SDK同步更新，可能会出问题。

2. tangram暴露解析，然后接入方自行解析，tangram只负责摆放card。优点是，可以适配所有接入方的数据。缺点是，边界可控性方面待商榷(接入方返回的card合法性，字段判空等。)。

**Comment by longerian** [comment]
嗯  这个要取舍 平衡一下的

**Comment by liufsd** [comment]
恩，我这点选择上，陷入了一个两难的尴尬局面。
所以，您更倾向于哪一种呢？
如果是1，那就要接入方自己写转换代码了的，如果接口比如多的话，确实比较麻烦的。
如果是2，那么需要改下TangramBuilder初始化的时候，容许自行解析了的。

**Comment by liufsd** [comment]
如果是2：
大概需要改动这些地方：
```
    /**
     * init a {@link TangramEngine} builder with build-in resource inited, such as registering build-in card and cell. Users use this builder to regiser custom card and cell, then call {@link InnerBuilder#build()} to create a {@link TangramEngine} instance.
     * @param context activity context
     * @return a {@link TangramEngine} builder
     */
    @NonNull
    public static InnerBuilder newInnerBuilder(@NonNull final Context context ) {
        if (!TangramBuilder.isInitialized()) {
            throw new IllegalStateException("Tangram must be init first");
        }

        DefaultResolverRegistry registry = new DefaultResolverRegistry();

        // install default cards & mCells
        installDefaultRegistry(registry);

        return new InnerBuilder(context, registry);
    }
```

追加一个PojoDataParser参数的方法，然后builder里面取一下，默认是走七巧板SDK内部的解析。

需要我来改，还是你那边直接改呢？

**Comment by liufsd** [comment]
因为明天开始就要正式动工了的，之前一直属于调研阶段，中间耽搁了一段时间，之后干脆就等你们2.0发布了的。哈哈哈。
明天开始要搭架子了的，所以数据处理这一层还是相当重要的一个环节。

**Comment by liufsd** [comment]
效率很赞，看到您改好了的。
能打个release嘛？我这边可以直接用起来啦。现在是maven依赖2.0.2版本。希望打一个2.0.3版本。

**Comment by liufsd** [comment]
Card中的serviceManager，需要改成public，否则无法构造。

**Comment by liufsd** [comment]
Card解析cell这个过程，其实也应该向外暴露的。因为字段名称可能不叫‘items’.

**Comment by longerian** [comment]
每周打一次吧 不然太频繁了，小版本太多
serviceManager可以从tangramengine里获取的
『Card解析cell这个过程，其实也应该向外暴露的。因为字段名称可能不叫‘items’.』这个改动有点大，暂时没想好，你先考虑考虑，抽象一下不影响现有使用方。

**Comment by liufsd** [comment]
好的。

**Comment by liufsd** [comment]
似乎不太行。
Card 里面，如果serviceManager没有赋值的话，这里来会crash的。
```
    public void parseWith(@NonNull JSONObject data, @NonNull final MVHelper resolver, boolean isParseCell) {
        if (TangramBuilder.isPrintLog()) {
            if (serviceManager == null) {
                throw new RuntimeException("serviceManager is null when parsing card");
            }
        }
```

**Comment by longerian** [comment]
明白了

**Comment by liufsd** [comment]
是的，我先替了一个merge request #67  你可以看下，顺带我也追加了一个demo进去，这样可以方便大家调试使用

**Comment by longerian** [comment]
@liufsd 你可以同步代码源码依赖，等我发布再更新，或者定期同步源码，否则每改一个地方就发个版本，长期下来也玩不转。

**Comment by liufsd** [comment]
确实。先源码依赖吧。你可以把 #67 先merge到develop。我以这个commit为基准去依赖吧。

**Comment by longerian** [comment]
好了，以后demo里代码测试最好不用合过来

**Comment by liufsd** [comment]
好，其实我是想，补充一个demo进去，跟ios对齐。
其实现在demo应该有两个入口：
从view构建考虑：
1.本地写xml
2.动态下发
从解析处理：
1.SDK默认解析
2.自己定义解析。

还有我今天已经源码依赖的方式，进行开发了的。等稳定后，直接替换成你们的maven版本即可。这样我也可以发现问题，修复问题。一起维护。

**Comment by longerian** [comment]
发了 2.0.3
