### ISSUE TITLE
分页加载会在分页的最后一条和下一页的第一条显示重复

### ISSUE THREAD

**Issue by wht0707** [alibaba/Tangram-Android#69]
# #[

](url)
![111](https://user-images.githubusercontent.com/26018016/33978285-e9da8724-e0d9-11e7-97d6-c10033c7bb44.png)

**Comment by longerian** [comment]
那一定是数据重复了，解析出来的baseCell对象肯定有两份，你先确认下这个问题

**Comment by wht0707** [comment]
是后台接口数据重复了,已解决。抱歉忘记告诉您了!

**Comment by longerian** [comment]
那就好 看到了，感谢支持
