### ISSUE TITLE
多个Bannner配置无效

### ISSUE THREAD

**Issue by kanliuzuoyou** [alibaba/Tangram-Android#77]
出现多个bannerCard的时候，如果配置了自动轮播，其他的轮播不配置自动轮播也会自动滑动

**Comment by liufsd** [comment]
是不是其他几个时间没有配置？develop分支已经fix了这个问题，banner复用问题导致的。

**Comment by longerian** [comment]
@kanliuzuoyou  不知道你用的是哪个版本，这个已经由 @liufsd 修复过了 使用最新的版本即可

**Comment by kanliuzuoyou** [comment]
好的，还有LinearScrollCard也会出现数据错乱的情况，是不是还存在复用的问题，我两个LinearScrollCard初始化的使用发生数据重复错乱

**Comment by liufsd** [comment]
“数据重复错乱”  也是一个bug， 修复了的。 可以看下develop分支的代码提交记录。

**Comment by longerian** [comment]
v2.0.4
