### ISSUE TITLE
webview 复用找不到该item

### ISSUE THREAD

**Issue by yubaokang** [alibaba/Tangram-Android#78]
item 数据展示

item_webview1 (长页面)
item_webview2 (长页面)
item1
item2
item3
...
item10

操作：
1：从上浏览到下，没有问题
2：滑动到底之后，再重新滑动到上，滑动到item1完全展示的之后，直接显示了item10，然后一直滑不到顶，在item1和item10之间循环显示，两个webview消失了。

这个问题如何排查。具体是哪里出现了问题

**Comment by yubaokang** [comment]
@longerian

**Comment by liufsd** [comment]
你试试源码依赖，最新的代码修复了复用问题。

**Comment by yubaokang** [comment]
setJavaScriptEnabled 这个方法导致

**Comment by liufsd** [comment]
ok
