### ISSUE TITLE
Tangram 图片加载框架优先使用Picasso，与Glide不兼容【Bug】

### ISSUE THREAD

**Issue by yanyusong** [alibaba/Tangram-Android#8]
详细问题描述写在vLayout里了[issues87](https://github.com/alibaba/vlayout/issues/87)，

解决方案是：在Tangram里使用Picasso，不要使用Glide

**Comment by longerian** [comment]
@yanyusong 用demo工程跑了一下，暂时没复现这个问题。
大概看了一下Glide源码，可能和他加载完毕需要做一次transition有关，在界面来回滑动，imageview复用的情况下，还要做动画，需要做好图片加载、取消的管理工作。你可以沿着这个思路再查一下。

**Comment by maolubin** [comment]
Picasso 不支持gif啊

**Comment by yubaokang** [comment]
这个问题怎么处理？
