### ISSUE TITLE
FloatCard 怎么控制拖拽显示范围？

### ISSUE THREAD

**Issue by bitterking** [alibaba/Tangram-Android#81]
如题，设置margin之后，cell中的view会被挤压，
设置setFixOffset后，发现FloatLayoutHelper 里面又被注释掉了~~

**Comment by longerian** [comment]
设置margin是上下被挤压，还是左右被挤压。被挤压的问题应该可以修复

**Comment by bitterking** [comment]
都被挤压，有点不太明白setFixOffset 这个的意义按理说应该就是限定FloatCard的拖拽范围么？我有什么办法设置么

**Comment by longerian** [comment]
是的 会限定四边的范围，但是那个会影响其他Sticky  Fix 类型的Card

**Comment by bitterking** [comment]
但是我看FloatLayoutHelper 里面的实现，拖拽是没有计算这个fixOffset的，不知道基于什么考虑，有没有方法可以让FloatCard固定位置显示呢？

**Comment by longerian** [comment]
还是用margin来控制吧，fixOffset只控制起始位置。我把设置了margin被挤压的问题改了一下。可以把vlayout替换成1.2.6.3版本就行了。
