### ISSUE TITLE
master分支提示找不到符号

### ISSUE THREAD

**Issue by Jadyli** [alibaba/Tangram-Android#82]
/Users/jady/StudioProjects/Tangram-Android/examples/src/main/java/com/tmall/wireless/tangram/example/TangramDataParserActivity.java
Error:(112, 19) 错误: 找不到符号
符号:   方法 loadImageLoader(Context)
位置: 类 VafContext

![image](https://user-images.githubusercontent.com/15962904/34659127-2e25ab8a-f470-11e7-99b0-a6ff68707c72.png)

**Comment by WilliamQin7** [comment]
+1, 是否demo需要更新？我在尝试把VirtualView版本降级为1.0.1后方可正常编译

**Comment by longerian** [comment]
sorry 我重构了virtualview的图片加载，已经提交了。
