### ISSUE TITLE
在 Tangram 中使用 VirtualView注事件处理器，BaseCell的onClick方法中没有处理相应事件

### ISSUE THREAD

**Issue by jiangzhengnan** [alibaba/Tangram-Android#90]
在tangram中注册事件的方式：
    private VafContext sVafContext;
      //初始化sVafContext
        sVafContext = engine.getService(VafContext.class);
        //注册监听器
        sVafContext.getEventManager().register(EventManager.TYPE_Click, new EventProcessor());

但是点击了组件并没有回调，后来发现在BaseCell的OnClick方法中：
    @Override
    public void onClick(View v) {
        if (serviceManager != null) {
            SimpleClickSupport service = serviceManager.getService(SimpleClickSupport.class);
            if (service != null) {
                int eventType = this.pos;
                if (innerClickMap.containsKey(v.hashCode())) {
                    eventType = innerClickMap.get(v.hashCode()).intValue();
                }
                service.onClick(v, this, eventType);
            }
        }
    }
只对注册SimpleClickSupport的方式进行了处理，所以VirtualView的事件注册机制无法执行？

**Comment by MikeAfc** [comment]
VafContext vafContext = tangramEngine.getService(VafContext.class);
vafContext.getEventManager().register(EventManager.TYPE_Click, new IEventProcessor() {

    @Override
    public boolean process(EventData data) {
        //handle here
        return true;
    }
});
