### ISSUE TITLE
滑动卡顿一下

### ISSUE THREAD

**Issue by tanghb** [alibaba/Tangram-Android#98]
从上往下滑动时，流畅，但是从下面网上再滑动回去的时候，会卡顿一下。
最上面是用的Banner，紧接着是用的container-flow，就是这个container-flow会稍微卡顿一下，其它地方都不卡。我以为是container-flow的问题，但是换成container-fiveColumn仍然会卡顿一下。
这是什么原因呢。。

`[{
	"style": {
		"autoScroll": "5000",
		"indicatorGap": "2",
		"indicatorGravity": "right",
		"indicatorHeight": "1.5",
		"indicatorImg1": "https:\/\/img.alicdn.com\/tps\/TB16i4qNXXXXXbBXFXXXXXXXXXX-32-4.png",
		"indicatorImg2": "https:\/\/img.alicdn.com\/tps\/TB1XRNFNXXXXXXKXXXXXXXXXXXX-32-4.png",
		"indicatorMargin": "5",
		"infinite": "true"
	},
	"items": [{
		"key_data_model": {
			"banner_height": 240,
			"image_height": 328,
			"img_url": "XXX",
			"link": "XXX",
			"position": 0
		},
		"type": "home_banner"
	}, {
		"key_data_model": {
			"banner_height": 240,
			"image_height": 328,
			"img_url": "XXX",
			"link": "XXX",
			"position": 1
		},
		"type": "home_banner"
	}],
	"type": "container-banner"
}, {
	"style": {
		"bgColor": "#FFFFFF",
		"margin": [null, null, 6, null],
		"padding": [7, 12, 8, 12]
	},
	"items": [{
		"style": {
			"bgColor": "#FFFFFF",
			"column": 5,
			"padding": [7, null, 8, null]
		},
		"items": [{
			"key_data_model": {
				"icon_id": "31",
				"title": "我的首页"
			},
			"type": "home-kong-kim"
		}, {
			"key_data_model": {
				"icon_id": "4",
				"title": "title1"
			},
			"type": "home-kong-kim"
		}, {
			"key_data_model": {
				"icon_id": "31",
				"title": "title3"
			},
			"type": "home-kong-kim"
		}, {
			"key_data_model": {
				"icon_id": "4",
				"title": "title3"
			},
			"type": "home-kong-kim"
		}, {
			"key_data_model": {
				"icon_id": "4",
				"title": "title4"
			},
			"type": "home-kong-kim"
		}],
		"type": "container-flow"
	}, {
		"style": {
			"bgColor": "#FFFFFF",
			"column": 5,
			"padding": [7, null, 8, null]
		},
		"items": [{
			"key_data_model": {
				"icon_id": "31",
				"title": "title5"
			},
			"type": "home-kong-kim"
		}, {
			"key_data_model": {
				"icon_id": "4",
				"title": "title6"
			},
			"type": "home-kong-kim"
		}, {
			"key_data_model": {
				"icon_id": "31",
				"title": "title7"
			},
			"type": "home-kong-kim"
		}, {
			"key_data_model": {
				"icon_id": "4",
				"title": "title8"
			},
			"type": "home-kong-kim"
		}, {
			"key_data_model": {
				"icon_id": "4",
				"title": "title9"
			},
			"type": "home-kong-kim"
		}],
		"type": "container-flow"
	}],
	"type": "container-oneColumn"
},{
	...
}]`

**Comment by tanghb** [comment]
这个找到原因了，需要设置下RecyclerView的复用池。
`this.recyclerView.getRecycledViewPool().setMaxRecycledViews(i, size);`
但是，注意，需要在`engine.bindView(recyclerView);`之后设置

**Comment by flyer1b** [comment]
问一下你设置复用池的那个i怎么设的

**Comment by tanghb** [comment]
就是一个for循环，总数是页面中View的类型总数
